// src/components/RevenueGenerated.js
import React from 'react';
import '../styles/RevenueGenerated.css';

const RevenueGenerated = () => {
  return (
    <div className="revenue-generated-container">
      <h2>Revenue Generated</h2>
      <p>This section provides insights into the revenue generated by your business through successful deals.</p>
      <div className="revenue-details">
        <h3>Total Revenue: ₹1,00,000</h3>
        <p>Revenue generated from completed deals, product sales, and other business activities.</p>
        <h3>Top Performing Products:</h3>
        <ul>
          <li>Product A - ₹40,000</li>
          <li>Product B - ₹30,000</li>
          <li>Product C - ₹20,000</li>
          <li>Service D - ₹10,000</li>
        </ul>
      </div>
    </div>
  );
};

export default RevenueGenerated;
